"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { NodoApiClient, NodoApiError } from "@nodo/api-client";

const apiUrl = process.env.NEXT_PUBLIC_NODO_API_URL ?? "http://127.0.0.1:8000/api/v1";
function errorMessage(error: unknown) { if (error instanceof NodoApiError) { if (error.status === 403) return "El registro local está desactivado en la API."; if (error.status === 409) return "Ese correo ya tiene una cuenta."; if (error.status === 422) return "Revisa los datos y la zona horaria."; return error.message; } return "No fue posible crear la cuenta. Verifica que la API esté activa."; }

export default function Register() {
  const [form, setForm] = useState({ email: "", first_name: "", last_name: "", password: "", timezone: "America/Mexico_City" }); const [error, setError] = useState<string | null>(null); const [submitting, setSubmitting] = useState(false); const [created, setCreated] = useState(false);
  function update(field: keyof typeof form, value: string) { setForm((current) => ({ ...current, [field]: value })); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(null); setSubmitting(true); try { await new NodoApiClient(apiUrl).request("/auth/coaches", { method: "POST", body: form }); setCreated(true); } catch (reason) { setError(errorMessage(reason)); } finally { setSubmitting(false); } }
  return <main className="appShell authShell"><div className="orb orbOne" /><div className="orb orbTwo" /><header className="topbar"><Link className="brand" href="/"><span className="brandDot" />NODO</Link><Link className="textButton" href="/login">Ya tengo acceso <span>↗</span></Link></header><section className="registerLayout"><div className="authIntro"><div className="heroKicker"><span>DEV</span> LOCAL COACH BOOTSTRAP</div><h1>Abre tu<br /><em>primer nodo.</em></h1><p>Este registro está disponible sólo para probar NODO en desarrollo local. No crea cuentas públicas.</p></div>{created ? <section className="loginCard successCard"><p className="eyebrow">ACCESS NODE / READY</p><h2>Cuenta<br />creada.</h2><p className="successCopy">Tu identidad de entrenador ya está lista. Entra a NODO para abrir tu espacio.</p><Link className="primary registerButton" href="/login"><span>IR AL LOGIN</span><b>↗</b></Link></section> : <form className="loginCard" onSubmit={submit}><div className="cardTop"><div><p className="eyebrow">CREATE COACH / 001</p><h2>Crear<br />cuenta.</h2></div><span className="devBadge">DEV ONLY</span></div><div className="registerFields"><label><span>NOMBRE</span><input value={form.first_name} onChange={(event) => update("first_name", event.target.value)} required /></label><label><span>APELLIDO</span><input value={form.last_name} onChange={(event) => update("last_name", event.target.value)} required /></label></div><label><span>EMAIL</span><input type="email" autoComplete="email" placeholder="coach@nodo.run" value={form.email} onChange={(event) => update("email", event.target.value)} required /></label><label><span>CLAVE / 12+ CARACTERES</span><input type="password" autoComplete="new-password" value={form.password} onChange={(event) => update("password", event.target.value)} minLength={12} required /></label><label><span>ZONA HORARIA</span><select value={form.timezone} onChange={(event) => update("timezone", event.target.value)}><option value="America/Mexico_City">America/Mexico_City</option><option value="America/New_York">America/New_York</option><option value="Europe/Madrid">Europe/Madrid</option><option value="UTC">UTC</option></select></label>{error && <p className="error" role="alert"><strong>!</strong>{error}</p>}<button className="primary" type="submit" disabled={submitting}><span>{submitting ? "CREANDO IDENTIDAD" : "CREAR CUENTA LOCAL"}</span><b>↗</b></button><p className="helper">El endpoint permanece protegido por el entorno de desarrollo.</p></form>}</section><footer className="footerLine"><span>NODO TRAINING SYSTEMS / 2026</span><span>DEVELOPMENT ONLY <i /></span></footer></main>;
}
