"use client";

import { FormEvent, useEffect, useState } from "react";
import { ContractState, EmptyState, ErrorState, PageHeader, StatusBadge } from "./ui";
import { isContractUnavailable, nodoRequest, problemFrom } from "@/lib/api";
import { featureContracts } from "@/lib/feature-contracts";

type ReviewItem = { id: number; kind: string; priority: string; reason: string; status: string; athlete_name?: string };
export function ReviewWorkspace() {
  const [items, setItems] = useState<ReviewItem[]>([]); const [unavailable, setUnavailable] = useState(false); const [error, setError] = useState<string | null>(null); const [notes, setNotes] = useState<Record<number, string>>({});
  useEffect(() => { void nodoRequest<ReviewItem[]>("review-items").then(setItems).catch((reason) => { if (isContractUnavailable(reason)) setUnavailable(true); else setError(problemFrom(reason).message); }); }, []);
  async function update(item: ReviewItem, status: "reviewed" | "follow_up" | "closed") { const note = notes[item.id]?.trim(); if (!note) { setError("Agrega una nota antes de decidir."); return; } try { const next = await nodoRequest<ReviewItem>(`review-items/${item.id}/decision`, { method: "POST", body: { status, note } }); setItems((current) => current.filter((candidate) => candidate.id !== next.id)); } catch (reason) { setError(problemFrom(reason).message); } }
  return <div className="page"><PageHeader eyebrow="NODO Lab / Atención" title="Bandeja de revisión" description="Ordena situaciones por una razón visible. Una molestia nueva o que empeora nunca queda oculta por otros datos." />{unavailable ? <ContractState title={featureContracts.review.label} description="No se muestran prioridades sintéticas. La bandeja aparecerá cuando el servicio pueda calcular y deduplicar casos reales." expected={featureContracts.review.expected} /> : error && !items.length ? <ErrorState message={error} /> : items.length ? <div className="stack">{error ? <ErrorState message={error} /> : null}{items.map((item) => <article className="card stack" key={item.id}><div className="cluster" style={{ justifyContent: "space-between" }}><StatusBadge tone={item.priority === "high" ? "coral" : "info"}>{item.kind} · {item.priority}</StatusBadge><span className="metadata">{item.status}</span></div><h2>{item.athlete_name ?? `Atleta ${"athlete_id" in item ? String((item as ReviewItem & { athlete_id: number }).athlete_id) : ""}`}</h2><p className="muted">{item.reason}</p><label className="field"><span className="field-label">Nota de decisión</span><textarea className="textarea" value={notes[item.id] ?? ""} onChange={(event) => setNotes((current) => ({ ...current, [item.id]: event.target.value }))} required /></label><div className="cluster"><button className="button button-primary" disabled={!notes[item.id]?.trim()} onClick={() => update(item, "reviewed")}>Marcar revisado</button><button className="button" disabled={!notes[item.id]?.trim()} onClick={() => update(item, "follow_up")}>Dar seguimiento</button><button className="button" disabled={!notes[item.id]?.trim()} onClick={() => update(item, "closed")}>Cerrar</button></div></article>)}</div> : <EmptyState title="No hay situaciones pendientes." copy="Cuando existan señales reales, aparecerán con su razón, fuente y antigüedad." />}</div>;
}

type SimulatedSession = { day: string; title: string; purpose: string; structure: string };
export function CopilotWorkspace() {
  const [prompt, setPrompt] = useState(""); const [draft, setDraft] = useState<SimulatedSession[] | null>(null);
  function simulate(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const focus = prompt.toLowerCase().includes("10k") ? "10K" : prompt.toLowerCase().includes("800") ? "800–1500 m" : "objetivo descrito"; setDraft([{ day: "Lunes", title: "Rodaje de base", purpose: `Construir continuidad para ${focus}`, structure: "45 min suaves + 4 progresiones" }, { day: "Miércoles", title: "Sesión específica", purpose: "Trabajar la demanda principal sin asumir ritmos", structure: "Calentamiento + bloque por definir + vuelta a la calma" }, { day: "Viernes", title: "Recuperación", purpose: "Mantener frecuencia con baja exigencia", structure: "30 min muy suaves" }, { day: "Domingo", title: "Rodaje largo", purpose: "Sostener volumen dentro de disponibilidad", structure: "Duración a confirmar con el entrenador" }]); }
  return <div className="page page-narrow"><PageHeader eyebrow="NODO Lab / Copiloto" title="Convierte una intención en borrador." description="Modo simulado local: ayuda a revisar el flujo sin proveedor, costo, datos reales ni escritura en la base." /><div className="alert alert-info"><strong>SIMULACIÓN.</strong> La salida no usa un modelo, no consulta atletas y no se puede publicar. Los campos sin contexto permanecen explícitamente pendientes.</div><form className="card stack" onSubmit={simulate} style={{ marginTop: 16 }}><label className="field"><span className="field-label">Describe objetivo, disponibilidad y restricciones</span><textarea className="textarea" value={prompt} onChange={(event) => setPrompt(event.target.value)} placeholder="Ej. seis semanas para 10K, cuatro sesiones, sin correr martes…" required /></label><button className="button button-primary">Generar borrador simulado</button></form>{draft ? <section className="stack" style={{ marginTop: 18 }}><div className="cluster" style={{ justifyContent: "space-between" }}><h2>Borrador no guardado</h2><StatusBadge tone="info">SIMULACIÓN</StatusBadge></div>{draft.map((session) => <article className="card" key={session.day}><span className="eyebrow">{session.day}</span><h3>{session.title}</h3><p>{session.structure}</p><p className="helper">Intención: {session.purpose}</p></article>)}<div className="alert">Para convertir esto en un plan real hacen falta un proveedor aprobado, validación de esquema, contexto autorizado y revisión del entrenador.</div></section> : null}</div>;
}

type Recommendation = { id: number; status: string; athlete_id: number; workout_id: number; title?: string; changes?: { title?: string }; base_plan_version?: number };
export function RecommendationsWorkspace() {
  const [items, setItems] = useState<Recommendation[]>([]); const [error, setError] = useState<string | null>(null); const [form, setForm] = useState({ athlete_id: "", workout_id: "", title: "" });
  useEffect(() => { void nodoRequest<Recommendation[]>("recommendations").then(setItems).catch((reason) => setError(problemFrom(reason).message)); }, []);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(null); try { const result = await nodoRequest<{ id: number; status: string }>("recommendations", { method: "POST", body: { athlete_id: Number(form.athlete_id), workout_id: Number(form.workout_id), evidence: [], changes: { title: form.title } } }); setItems((current) => [{ ...result, athlete_id: Number(form.athlete_id), workout_id: Number(form.workout_id), title: form.title }, ...current]); setForm({ athlete_id: "", workout_id: "", title: "" }); } catch (reason) { setError(problemFrom(reason).message); } }
  async function decide(item: Recommendation, action: "approve" | "reject") { try { const result = await nodoRequest<{ status: string }>(`recommendations/${item.id}/decision`, { method: "POST", body: { action, note: null } }); setItems((current) => current.map((candidate) => candidate.id === item.id ? { ...candidate, status: result.status } : candidate)); } catch (reason) { const problem = problemFrom(reason); setError(problem.status === 409 ? "La propuesta quedó obsoleta porque el plan cambió. Recalcula antes de decidir." : problem.message); } }
  return <div className="page"><PageHeader eyebrow="NODO Lab / Decisiones" title="Propuestas" description="Crea un cambio acotado sobre una sesión borrador y decídelo con control de versión en el servidor." /><div className="split"><section className="stack">{error ? <ErrorState message={error} /> : null}{items.length ? items.map((item) => <article className="card stack" key={item.id}><div className="cluster" style={{ justifyContent: "space-between" }}><StatusBadge tone={item.status === "pending" ? "info" : "signal"}>{item.status}</StatusBadge><span className="metadata">Sesión {item.workout_id} · base v{item.base_plan_version ?? "—"}</span></div><h2>{item.title ?? item.changes?.title ?? "Propuesta de ajuste"}</h2><p className="muted">Propuesta {item.id} para atleta {item.athlete_id}. La aprobación falla con 409 si la versión base cambió.</p>{item.status === "pending" ? <div className="cluster"><button className="button button-primary" onClick={() => decide(item, "approve")}>Aprobar cambio</button><button className="button button-danger" onClick={() => decide(item, "reject")}>Rechazar</button></div> : null}</article>) : <EmptyState title="No hay propuestas." copy="El calendario manual sigue disponible aunque no haya recomendaciones pendientes." />}</section><form className="card stack" onSubmit={create}><h2>Proponer cambio de título</h2><label className="field"><span className="field-label">ID atleta</span><input className="input" type="number" min="1" value={form.athlete_id} onChange={(event) => setForm({ ...form, athlete_id: event.target.value })} required /></label><label className="field"><span className="field-label">ID sesión borrador</span><input className="input" type="number" min="1" value={form.workout_id} onChange={(event) => setForm({ ...form, workout_id: event.target.value })} required /></label><label className="field"><span className="field-label">Nuevo título</span><input className="input" value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} required /></label><button className="button button-primary">Crear propuesta</button></form></div></div>;
}

type NamedResource = { id: number; name?: string; title?: string; description?: string; member_count?: number; status?: string };
export function NamedResourcesWorkspace({ kind }: { kind: "groups" | "templates" }) {
  const contract = kind === "groups" ? featureContracts.groups : featureContracts.templates;
  const [items, setItems] = useState<NamedResource[]>([]); const [error, setError] = useState<string | null>(null); const [name, setName] = useState(""); const [sport, setSport] = useState("running"); const [sessionTitle, setSessionTitle] = useState(""); const [date, setDate] = useState(new Date().toISOString().slice(0, 10));
  useEffect(() => { void nodoRequest<NamedResource[]>(contract.endpoint).then(setItems).catch((reason) => setError(problemFrom(reason).message)); }, [contract.endpoint]);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(null); try { const body = kind === "groups" ? { name } : { name, sport_type: sport, workouts: [{ key: "session-1", title: sessionTitle, description: null, scheduled_date: new Date(`${date}T12:00:00Z`).toISOString(), sport_type: sport, block_id: null, steps: [{ repetitions: 1, steps: [{ kind: "work", duration_sec: 1800 }] }] }] }; const created = await nodoRequest<NamedResource>(contract.endpoint, { method: "POST", body }); setItems((current) => [...current, created]); setName(""); setSessionTitle(""); } catch (reason) { setError(problemFrom(reason).message); } }
  return <div className="page"><PageHeader eyebrow={`NODO Lab / ${contract.label}`} title={contract.label} description={kind === "groups" ? "Organiza atletas sin perder sus excepciones individuales." : "Reutiliza estructura con sesiones validadas por el servidor."} /><div className="split"><section className="stack">{error ? <ErrorState message={error} /> : null}{items.length ? items.map((item) => <article className="card" key={item.id}><StatusBadge tone="signal">guardado</StatusBadge><h2>{item.name ?? item.title}</h2><p className="muted">ID servidor: {item.id}</p></article>) : <EmptyState title={`No hay ${contract.label.toLowerCase()}.`} copy="Crea el primer elemento para empezar." />}</section><form className="card stack" onSubmit={create}><h2>Crear {kind === "groups" ? "grupo" : "plantilla"}</h2><label className="field"><span className="field-label">Nombre</span><input className="input" value={name} onChange={(event) => setName(event.target.value)} required /></label>{kind === "templates" ? <><label className="field"><span className="field-label">Deporte</span><select className="select" value={sport} onChange={(event) => setSport(event.target.value)}><option value="running">Carrera</option><option value="cycling">Ciclismo</option><option value="swimming">Natación</option><option value="triathlon">Triatlón</option></select></label><label className="field"><span className="field-label">Primera sesión</span><input className="input" value={sessionTitle} onChange={(event) => setSessionTitle(event.target.value)} required /></label><label className="field"><span className="field-label">Fecha base</span><input className="input" type="date" value={date} onChange={(event) => setDate(event.target.value)} required /></label><p className="helper">Se crea una plantilla mínima de 30 minutos; podrás ampliarla cuando exista edición de plantillas.</p></> : null}<button className="button button-primary">Guardar en servidor</button></form></div></div>;
}
