"use client";

import { FormEvent, useEffect, useState } from "react";
import { ContractState, EmptyState, ErrorState, PageHeader, StatusBadge } from "./ui";
import { isContractUnavailable, nodoRequest, problemFrom } from "@/lib/api";
import { GroupsWorkspace, TemplatesWorkspace } from "./resources-workspace";
import { ManualRecommendationsWorkspace } from "./recommendations-workspace";
import { ComplaintEvolution, type ComplaintRecord } from "./complaint-evolution";
import type { Athlete } from "@/lib/contracts";
import { featureContracts } from "@/lib/feature-contracts";

type ReviewItem = { id: number; version: number; athlete_id: number; complaint_id: number | null; kind: string; priority: string; reason: string; status: string; athlete_name?: string };
export function ReviewWorkspace() {
  const [items, setItems] = useState<ReviewItem[]>([]); const [unavailable, setUnavailable] = useState(false); const [error, setError] = useState<string | null>(null); const [athletes,setAthletes]=useState<Athlete[]>([]);const [complaints,setComplaints]=useState<Record<number,ComplaintRecord>>({}); const [notes, setNotes] = useState<Record<number, string>>({});
  useEffect(() => { void nodoRequest<Athlete[]>("auth/athletes").then(setAthletes).catch(()=>{}); void nodoRequest<ReviewItem[]>("review-items").then(setItems).catch((reason) => { if (isContractUnavailable(reason)) setUnavailable(true); else setError(problemFrom(reason).message); }); }, []);
  async function update(item: ReviewItem, status: "reviewed" | "follow_up" | "closed") { const note = notes[item.id]?.trim(); if (!note) { setError("Agrega una nota antes de decidir."); return; } try { const next = await nodoRequest<ReviewItem>(`review-items/${item.id}/decision`, { method: "POST", body: { status, note, expected_version: item.version } }); setItems((current) => status === "follow_up" ? current.map(c => c.id===next.id ? next : c) : current.filter((candidate) => candidate.id !== next.id)); } catch (reason) { setError(problemFrom(reason).message); } }
  return <div className="page"><PageHeader eyebrow="NODO Lab / Atención" title="Bandeja de revisión" description="Ordena situaciones por una razón visible. Una molestia nueva o que empeora nunca queda oculta por otros datos." />{unavailable ? <ContractState title={featureContracts.review.label} description="No se muestran prioridades sintéticas. La bandeja aparecerá cuando el servicio pueda calcular y deduplicar casos reales." expected={featureContracts.review.expected} /> : error && !items.length ? <ErrorState message={error} /> : items.length ? <div className="stack">{error ? <ErrorState message={error} /> : null}{items.map((item) => <article className="card stack" key={item.id}><div className="cluster" style={{ justifyContent: "space-between" }}><StatusBadge tone={item.priority === "high" ? "coral" : "info"}>{item.kind} · {item.priority}</StatusBadge><span className="metadata">{item.status}</span></div><h2>{athletes.find(a=>a.id===item.athlete_id) ? `${athletes.find(a=>a.id===item.athlete_id)?.first_name} ${athletes.find(a=>a.id===item.athlete_id)?.last_name}` : "Atleta asignado"}</h2><p className="muted">{item.reason}</p>{item.complaint_id ? complaints[item.complaint_id] ? <ComplaintEvolution item={complaints[item.complaint_id]} /> : <button className="button" onClick={()=>{ void nodoRequest<{complaint:ComplaintRecord}>(`complaints/${item.complaint_id}`).then(result=>setComplaints({...complaints,[result.complaint.id]:result.complaint})).catch(reason=>setError(problemFrom(reason).message)); }}>Ver molestia e historial</button> : null}<label className="field"><span className="field-label">Nota de decisión</span><textarea className="textarea" value={notes[item.id] ?? ""} onChange={(event) => setNotes((current) => ({ ...current, [item.id]: event.target.value }))} required /></label><div className="cluster"><button className="button button-primary" disabled={!notes[item.id]?.trim()} onClick={() => update(item, "reviewed")}>Marcar revisado</button><button className="button" disabled={!notes[item.id]?.trim()} onClick={() => update(item, "follow_up")}>Dar seguimiento</button><button className="button" disabled={!notes[item.id]?.trim()} onClick={() => update(item, "closed")}>Cerrar</button></div></article>)}</div> : <EmptyState title="No hay situaciones pendientes." copy="Cuando existan señales reales, aparecerán con su razón, fuente y antigüedad." />}</div>;
}

type SimulatedSession = { day: string; title: string; purpose: string; structure: string };
export function CopilotWorkspace() {
  const [prompt, setPrompt] = useState(""); const [draft, setDraft] = useState<SimulatedSession[] | null>(null);
  function simulate(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const focus = prompt.toLowerCase().includes("10k") ? "10K" : prompt.toLowerCase().includes("800") ? "800–1500 m" : "objetivo descrito"; setDraft([{ day: "Lunes", title: "Rodaje de base", purpose: `Construir continuidad para ${focus}`, structure: "45 min suaves + 4 progresiones" }, { day: "Miércoles", title: "Sesión específica", purpose: "Trabajar la demanda principal sin asumir ritmos", structure: "Calentamiento + bloque por definir + vuelta a la calma" }, { day: "Viernes", title: "Recuperación", purpose: "Mantener frecuencia con baja exigencia", structure: "30 min muy suaves" }, { day: "Domingo", title: "Rodaje largo", purpose: "Sostener volumen dentro de disponibilidad", structure: "Duración a confirmar con el entrenador" }]); }
  return <div className="page page-narrow"><PageHeader eyebrow="NODO Lab / Copiloto" title="Convierte una intención en borrador." description="Modo simulado local: ayuda a revisar el flujo sin proveedor, costo, datos reales ni escritura en la base." /><div className="alert alert-info"><strong>SIMULACIÓN.</strong> La salida no usa un modelo, no consulta atletas y no se puede publicar. Los campos sin contexto permanecen explícitamente pendientes.</div><form className="card stack" onSubmit={simulate} style={{ marginTop: 16 }}><label className="field"><span className="field-label">Describe objetivo, disponibilidad y restricciones</span><textarea className="textarea" value={prompt} onChange={(event) => setPrompt(event.target.value)} placeholder="Ej. seis semanas para 10K, cuatro sesiones, sin correr martes…" required /></label><button className="button button-primary">Generar borrador simulado</button></form>{draft ? <section className="stack" style={{ marginTop: 18 }}><div className="cluster" style={{ justifyContent: "space-between" }}><h2>Borrador no guardado</h2><StatusBadge tone="info">SIMULACIÓN</StatusBadge></div>{draft.map((session) => <article className="card" key={session.day}><span className="eyebrow">{session.day}</span><h3>{session.title}</h3><p>{session.structure}</p><p className="helper">Intención: {session.purpose}</p></article>)}<div className="alert">Para convertir esto en un plan real hacen falta un proveedor aprobado, validación de esquema, contexto autorizado y revisión del entrenador.</div></section> : null}</div>;
}

export const RecommendationsWorkspace = ManualRecommendationsWorkspace;
export function NamedResourcesWorkspace({ kind }: { kind: "groups" | "templates" }) { return kind === "groups" ? <GroupsWorkspace /> : <TemplatesWorkspace />; }
