"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Identity, NodoApiClient, NodoApiError, TokenPair } from "@nodo/api-client";

type StoredSession = TokenPair & { user: Identity };
const storageKey = "nodo.lab.session";
const apiUrl = process.env.NEXT_PUBLIC_NODO_API_URL ?? "http://127.0.0.1:8000/api/v1";

export default function NodoHome() {
  const router = useRouter(); const [session, setSession] = useState<StoredSession | null>(null); const [ready, setReady] = useState(false); const [error, setError] = useState<string | null>(null);
  useEffect(() => { const raw = window.sessionStorage.getItem(storageKey); if (!raw) { router.replace("/login"); return; } try { const stored = JSON.parse(raw) as StoredSession; void new NodoApiClient(apiUrl, stored.access_token).me().then((user) => { const next = { ...stored, user }; window.sessionStorage.setItem(storageKey, JSON.stringify(next)); setSession(next); setReady(true); }).catch(async (reason) => { if (reason instanceof NodoApiError && reason.status === 401) { try { const tokens = await new NodoApiClient(apiUrl).refresh(stored.refresh_token); const user = await new NodoApiClient(apiUrl, tokens.access_token).me(); const next = { ...tokens, user }; window.sessionStorage.setItem(storageKey, JSON.stringify(next)); setSession(next); setReady(true); return; } catch { /* redirigir abajo */ } } window.sessionStorage.removeItem(storageKey); router.replace("/login"); }); } catch { window.sessionStorage.removeItem(storageKey); router.replace("/login"); } }, [router]);
  async function signOut() { if (session) { try { await new NodoApiClient(apiUrl, session.access_token).logout(); } catch { /* la red puede estar inactiva */ } } window.sessionStorage.removeItem(storageKey); router.replace("/"); }
  if (!ready || !session) return <main className="loading"><span>ABRIENDO NODO</span></main>;
  return <main className="appShell nodoShell"><header className="topbar"><a className="brand" href="/"><span className="brandDot" />NODO</a><div className="nodoNav"><span className="liveStatus"><i /> SESIÓN ACTIVA</span><button className="textButton" onClick={signOut}>Salir <span>↗</span></button></div></header><section className="nodoHero"><div className="heroKicker"><span>01</span> YOUR TRAINING SPACE</div><h1>Hola, <em>{session.user.first_name}</em><span className="heroMark">✳</span></h1><p>Tu espacio para entender el día, ejecutar tu plan y mantener el hilo de tu progreso.</p></section><section className="nodoModules"><article className="moduleCard activeModule"><div className="moduleHeader"><span className="moduleNumber">01</span><span className="moduleStatus">ACTIVE NODE</span></div><div><p className="eyebrow">NODO / ATHLETE</p><h2>Entrenamiento<br />del día</h2><p className="moduleCopy">Aquí aparecerá tu sesión publicada y la información necesaria para ejecutarla.</p></div><span className="moduleArrow">↗</span></article><article className="moduleCard labModule"><div className="moduleHeader"><span className="moduleNumber">02</span><span className="moduleStatus">COACH MODE</span></div><div><p className="eyebrow">NODO LAB</p><h2>Planifica<br />mejor.</h2><p className="moduleCopy">Organiza atletas, bloques y sesiones estructuradas desde tu centro de mando.</p></div><a className="moduleLink" href="/lab">ABRIR NODO LAB <span>↗</span></a></article><article className="moduleCard mutedModule"><div className="moduleHeader"><span className="moduleNumber">03</span><span className="moduleStatus">COMING SOON</span></div><div><p className="eyebrow">SIGNALS</p><h2>Tu contexto<br />completo.</h2><p className="moduleCopy">Recuperación, molestias y conectores llegarán cuando sus datos estén listos.</p></div></article></section><footer className="footerLine"><span>NODO TRAINING SYSTEMS / 2026</span><span>API <i /> ONLINE</span></footer></main>;
}
